"use client";

import { ChangeEvent, FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";

type RecordKey = "messages" | "calendar";

type PageRecord = {
  id: string;
  record: RecordKey;
  page: number;
  totalPages: number;
  title: string;
  dates: string[];
  text: string;
};

type RecordMeta = {
  key: RecordKey;
  label: string;
  auth: string;
  generated: string;
  sha256: string;
  pages: number;
  expectedFilename: string;
};

type SearchResult = PageRecord & { score: number; snippet: string };
type PdfMap = Partial<Record<RecordKey, any>>;
type FileMap = Partial<Record<RecordKey, File>>;
type ProgressMap = Partial<Record<RecordKey, { current: number; total: number }>>;

const PDFJS_URL = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";
const PDFJS_WORKER_URL = "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const PIN_SHA256 = "75992a5ac67ff644d3063976c2effd10bdd93fcc109798e3d5c1acf2e530d01a";

const RECORDS: RecordMeta[] = [
  {
    key: "messages",
    label: "Complete Message Record",
    auth: "6HC5-QJM2-R7SL-S6PF",
    generated: "8/3/2026 at 11:31:52 AM",
    sha256: "0d9704ce4669f7a4aa8075f2bc65fbf139e03a88ce99735d772161ae58596886",
    pages: 1241,
    expectedFilename: "6HC5QJM2R7SLS6PF.pdf",
  },
  {
    key: "calendar",
    label: "Complete Calendar Record",
    auth: "BM9Q-9TYQ-UCXX-5YAU",
    generated: "8/3/2026 at 11:31:51 AM",
    sha256: "3cc4ec4154b1e2ce9e55fac8746177a1ca74ffbe8a2dcc36de7842e41195587a",
    pages: 99,
    expectedFilename: "BM9Q9TYQUCXX5YAU.pdf",
  },
];

const bytesToHex = (bytes: ArrayBuffer) =>
  Array.from(new Uint8Array(bytes))
    .map((byte) => byte.toString(16).padStart(2, "0"))
    .join("");

const sha256 = async (data: ArrayBuffer | string) => {
  const bytes = typeof data === "string" ? new TextEncoder().encode(data) : data;
  return bytesToHex(await crypto.subtle.digest("SHA-256", bytes));
};

const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

const termsFromQuery = (query: string) =>
  query
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .map((term) => term.trim())
    .filter((term) => term.length > 1);

const cleanText = (raw: string) => {
  const common = [
    /^Complete (?:Message|Calendar) Record/i,
    /^All times presented/i,
    /^Record Generated By TalkingParents/i,
    /^Unique Authentication Code/i,
    /^Page \d+ of \d+$/i,
  ];
  return raw
    .replace(/\u0002/g, "-")
    .replace(/\u00a0/g, " ")
    .split(/\r?\n/)
    .map((line) => line.trim().replace(/\s+/g, " "))
    .filter((line) => line && !common.some((pattern) => pattern.test(line)))
    .join("\n");
};

const extractTitle = (record: RecordKey, text: string, page: number) => {
  const lines = text.split("\n");
  if (record === "calendar") {
    for (const line of lines) {
      const match = line.match(/^Name:\s*(.+)$/);
      if (match) return match[1].slice(0, 160);
    }
    return page <= 3 ? "Record authentication and case information" : "Calendar record continuation";
  }
  for (let index = 1; index < lines.length; index += 1) {
    if (lines[index].startsWith("Created by:")) {
      const candidate = lines[index - 1];
      if (candidate.length < 180 && !candidate.endsWith("said:")) return candidate;
    }
  }
  if (page <= 3) return "Record authentication and case information";
  for (const line of lines) {
    if (["Messages", "Case Information", "Service Availability Notices", "New Message Notifications"].includes(line)) continue;
    if (/^(Mason Perry|Meagan Wedge)( viewed| on )/.test(line)) continue;
    if (line.length < 120) return line;
  }
  return "Message record continuation";
};

const pageDates = (text: string) => {
  const matches = text.match(/\b(?:1[0-2]|0?[1-9])\/(?:3[01]|[12]\d|0?[1-9])\/20\d{2}\b/g) ?? [];
  return Array.from(new Set(matches)).slice(0, 12);
};

const makeSnippet = (text: string, terms: string[]) => {
  const flat = text.replace(/\s+/g, " ").trim();
  if (!flat) return "No extractable text was found on this page.";
  if (!terms.length) return flat.slice(0, 360);
  const lower = flat.toLowerCase();
  const positions = terms.map((term) => lower.indexOf(term)).filter((value) => value >= 0);
  const first = positions.length ? Math.min(...positions) : 0;
  const start = Math.max(0, first - 130);
  const end = Math.min(flat.length, first + 300);
  return `${start > 0 ? "…" : ""}${flat.slice(start, end)}${end < flat.length ? "…" : ""}`;
};

function Highlight({ text, terms }: { text: string; terms: string[] }) {
  if (!terms.length) return <>{text}</>;
  const pattern = new RegExp(`(${terms.map(escapeRegex).join("|")})`, "gi");
  return (
    <>
      {text.split(pattern).map((part, index) =>
        terms.some((term) => part.toLowerCase() === term.toLowerCase()) ? (
          <mark key={`${part}-${index}`} className="rounded bg-amber-200 px-0.5 text-slate-950">
            {part}
          </mark>
        ) : (
          <span key={`${part}-${index}`}>{part}</span>
        ),
      )}
    </>
  );
}

function Stat({ label, value }: { label: string; value: ReactNode }) {
  return (
    <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-4">
      <div className="text-[10px] font-black uppercase tracking-[0.22em] text-cyan-300/70">{label}</div>
      <div className="mt-2 break-words text-sm font-bold text-white">{value}</div>
    </div>
  );
}

export default function TalkingParentsEvidencePortal() {
  const [pin, setPin] = useState("");
  const [accessGranted, setAccessGranted] = useState(false);
  const [unlockError, setUnlockError] = useState("");
  const [pages, setPages] = useState<PageRecord[]>([]);
  const [query, setQuery] = useState("");
  const [recordFilter, setRecordFilter] = useState<"all" | RecordKey>("all");
  const [loadedLabels, setLoadedLabels] = useState<Partial<Record<RecordKey, string>>>({});
  const [progress, setProgress] = useState<ProgressMap>({});
  const [viewer, setViewer] = useState<PageRecord | null>(null);
  const [rendering, setRendering] = useState(false);
  const [pdfError, setPdfError] = useState("");
  const [pdfJsReady, setPdfJsReady] = useState(false);
  const [zoom, setZoom] = useState(1.1);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const canvasWrapRef = useRef<HTMLDivElement | null>(null);
  const pdfDocsRef = useRef<PdfMap>({});
  const pdfFilesRef = useRef<FileMap>({});
  const objectUrlsRef = useRef<Partial<Record<RecordKey, string>>>({});

  useEffect(() => {
    const script = document.createElement("script");
    script.src = PDFJS_URL;
    script.async = true;
    script.onload = () => {
      const pdfjsLib = (window as any).pdfjsLib;
      if (pdfjsLib) {
        pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJS_WORKER_URL;
        setPdfJsReady(true);
      }
    };
    script.onerror = () => setPdfError("PDF renderer could not be loaded. Retry with an internet connection.");
    document.head.appendChild(script);
    return () => {
      script.remove();
      Object.values(objectUrlsRef.current).forEach((url) => url && URL.revokeObjectURL(url));
    };
  }, []);

  const unlock = async (event: FormEvent) => {
    event.preventDefault();
    setUnlockError("");
    const submitted = await sha256(pin);
    if (submitted !== PIN_SHA256) {
      setUnlockError("PIN rejected. Verify the four digits and retry.");
      return;
    }
    setPin("");
    setAccessGranted(true);
  };

  const lock = () => {
    setAccessGranted(false);
    setPages([]);
    setQuery("");
    setViewer(null);
    pdfDocsRef.current = {};
    pdfFilesRef.current = {};
    Object.values(objectUrlsRef.current).forEach((url) => url && URL.revokeObjectURL(url));
    objectUrlsRef.current = {};
    setLoadedLabels({});
    setProgress({});
  };

  const results = useMemo<SearchResult[]>(() => {
    const terms = termsFromQuery(query);
    const filtered = pages.filter((page) => recordFilter === "all" || page.record === recordFilter);
    if (!terms.length) return filtered.slice(0, 50).map((page) => ({ ...page, score: 0, snippet: makeSnippet(page.text, []) }));
    return filtered
      .map((page) => {
        const haystack = `${page.title}\n${page.text}`.toLowerCase();
        let score = 0;
        for (const term of terms) {
          const titleHits = page.title.toLowerCase().split(term).length - 1;
          const bodyHits = haystack.split(term).length - 1;
          if (!bodyHits) return null;
          score += titleHits * 12 + Math.min(bodyHits, 20) * 2;
        }
        if (haystack.includes(terms.join(" "))) score += 20;
        return { ...page, score, snippet: makeSnippet(page.text, terms) };
      })
      .filter((page): page is SearchResult => Boolean(page))
      .sort((a, b) => b.score - a.score || a.record.localeCompare(b.record) || a.page - b.page)
      .slice(0, 200);
  }, [pages, query, recordFilter]);

  const loadFiles = async (event: ChangeEvent<HTMLInputElement>) => {
    setPdfError("");
    if (!pdfJsReady) {
      setPdfError("PDF renderer is still loading. Wait a moment and select the files again.");
      return;
    }
    const files = Array.from(event.target.files ?? []);
    const pdfjsLib = (window as any).pdfjsLib;
    for (const file of files) {
      try {
        const bytes = await file.arrayBuffer();
        const fileHash = await sha256(bytes);
        const record = RECORDS.find((item) => item.sha256 === fileHash);
        if (!record) {
          setPdfError(`${file.name} does not match either ingested source receipt. SHA-256: ${fileHash}`);
          continue;
        }
        const doc = await pdfjsLib.getDocument({ data: bytes }).promise;
        if (doc.numPages !== record.pages) {
          setPdfError(`${file.name} matched a source hash but returned the wrong page count.`);
          continue;
        }
        if (objectUrlsRef.current[record.key]) URL.revokeObjectURL(objectUrlsRef.current[record.key] as string);
        pdfDocsRef.current[record.key] = doc;
        pdfFilesRef.current[record.key] = file;
        objectUrlsRef.current[record.key] = URL.createObjectURL(file);
        setLoadedLabels((current) => ({ ...current, [record.key]: `${file.name} · hash verified · ${doc.numPages} pages` }));
        setProgress((current) => ({ ...current, [record.key]: { current: 0, total: doc.numPages } }));

        const indexed: PageRecord[] = [];
        for (let pageNumber = 1; pageNumber <= doc.numPages; pageNumber += 1) {
          const sourcePage = await doc.getPage(pageNumber);
          const content = await sourcePage.getTextContent();
          const raw = content.items.map((item: any) => item.str ?? "").join("\n");
          const text = cleanText(raw);
          indexed.push({
            id: `${record.key}:${pageNumber}`,
            record: record.key,
            page: pageNumber,
            totalPages: doc.numPages,
            title: extractTitle(record.key, text, pageNumber),
            dates: pageDates(text),
            text,
          });
          if (pageNumber % 10 === 0 || pageNumber === doc.numPages) {
            setProgress((current) => ({ ...current, [record.key]: { current: pageNumber, total: doc.numPages } }));
            await new Promise((resolve) => setTimeout(resolve, 0));
          }
        }
        setPages((current) => [...current.filter((page) => page.record !== record.key), ...indexed]);
      } catch (error) {
        console.error(error);
        setPdfError(`Could not load ${file.name}. Confirm it is the original unmodified TalkingParents PDF.`);
      }
    }
    event.target.value = "";
  };

  const renderViewer = async (page: PageRecord, selectedZoom = zoom) => {
    setViewer(page);
    setRendering(true);
    setPdfError("");
    await new Promise((resolve) => requestAnimationFrame(resolve));
    const doc = pdfDocsRef.current[page.record];
    if (!doc) {
      setRendering(false);
      return;
    }
    try {
      const sourcePage = await doc.getPage(page.page);
      const wrapWidth = Math.max(280, (canvasWrapRef.current?.clientWidth ?? window.innerWidth - 32) - 24);
      const baseViewport = sourcePage.getViewport({ scale: 1 });
      const fitScale = Math.min(2.3, wrapWidth / baseViewport.width);
      const viewport = sourcePage.getViewport({ scale: fitScale * selectedZoom });
      const canvas = canvasRef.current;
      if (!canvas) return;
      const context = canvas.getContext("2d", { alpha: false });
      if (!context) return;
      const outputScale = Math.min(window.devicePixelRatio || 1, 2);
      canvas.width = Math.floor(viewport.width * outputScale);
      canvas.height = Math.floor(viewport.height * outputScale);
      canvas.style.width = `${Math.floor(viewport.width)}px`;
      canvas.style.height = `${Math.floor(viewport.height)}px`;
      await sourcePage.render({
        canvasContext: context,
        viewport,
        transform: outputScale === 1 ? undefined : [outputScale, 0, 0, outputScale, 0, 0],
      }).promise;
    } catch (error) {
      console.error(error);
      setPdfError("The selected source page could not be rendered.");
    } finally {
      setRendering(false);
    }
  };

  useEffect(() => {
    if (viewer && pdfDocsRef.current[viewer.record]) void renderViewer(viewer, zoom);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [zoom]);

  const openViewer = async (page: PageRecord) => {
    setZoom(1.1);
    await renderViewer(page, 1.1);
  };

  const openNativePdf = (page: PageRecord) => {
    const url = objectUrlsRef.current[page.record];
    if (!url) return;
    window.open(`${url}#page=${page.page}`, "_blank", "noopener,noreferrer");
  };

  const savePng = () => {
    const canvas = canvasRef.current;
    if (!canvas || !viewer) return;
    const link = document.createElement("a");
    link.download = `${viewer.record}-page-${String(viewer.page).padStart(4, "0")}.png`;
    link.href = canvas.toDataURL("image/png");
    link.click();
  };

  const copyCitation = async (page: PageRecord) => {
    const record = RECORDS.find((item) => item.key === page.record);
    if (!record) return;
    const citation = `TalkingParents ${record.label}, Unique Authentication Code ${record.auth}, generated ${record.generated}, page ${page.page} of ${record.pages}. SHA-256 of original PDF: ${record.sha256}.`;
    await navigator.clipboard.writeText(citation);
  };

  const terms = termsFromQuery(query);
  const indexedMessagePages = pages.filter((page) => page.record === "messages").length;
  const indexedCalendarPages = pages.filter((page) => page.record === "calendar").length;

  if (!accessGranted) {
    return (
      <main className="min-h-screen bg-[#071219] px-4 py-10 text-white sm:px-6">
        <div className="mx-auto max-w-xl">
          <div className="rounded-[32px] border border-cyan-300/20 bg-[#0d202a] p-6 shadow-2xl shadow-black/30 sm:p-8">
            <div className="text-xs font-black uppercase tracking-[0.3em] text-cyan-300">NULLWORKS / LEGALFLOW</div>
            <h1 className="mt-5 text-4xl font-black tracking-[-0.05em] sm:text-5xl">TalkingParents Evidence Portal</h1>
            <p className="mt-4 leading-7 text-slate-300">
              Mobile-first search and exact-page viewer for the authenticated TalkingParents message and calendar exports. The source PDFs and extracted text remain on your device.
            </p>
            <form onSubmit={unlock} className="mt-7">
              <label className="text-xs font-black uppercase tracking-[0.22em] text-slate-400" htmlFor="pin">Access PIN</label>
              <input
                id="pin"
                inputMode="numeric"
                autoComplete="one-time-code"
                value={pin}
                onChange={(event) => setPin(event.target.value.replace(/\D/g, "").slice(0, 8))}
                className="mt-3 w-full rounded-2xl border border-white/15 bg-black/30 px-5 py-4 text-center text-3xl font-black tracking-[0.45em] outline-none ring-cyan-300 focus:ring-2"
                placeholder="••••"
                aria-label="Access PIN"
              />
              <button type="submit" disabled={pin.length < 4} className="mt-4 w-full rounded-2xl bg-cyan-300 px-5 py-4 text-sm font-black uppercase tracking-[0.18em] text-slate-950 disabled:opacity-50">
                Unlock portal
              </button>
            </form>
            {unlockError && <div className="mt-4 rounded-2xl border border-red-400/30 bg-red-950/30 p-4 text-sm text-red-200">{unlockError}</div>}
            <div className="mt-6 rounded-2xl border border-amber-300/20 bg-amber-300/5 p-4 text-xs leading-6 text-amber-100/80">
              A four-digit PIN is a convenience gate, not strong access control. The private records are protected primarily by never hosting them: the original PDFs and search index remain local to the browser session.
            </div>
          </div>
        </div>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-[#071219] text-white">
      <div className="mx-auto max-w-7xl px-4 py-5 sm:px-6 lg:px-8">
        <header className="rounded-[28px] border border-white/10 bg-[#0d202a] p-5 shadow-xl shadow-black/20">
          <div className="flex flex-wrap items-start justify-between gap-4">
            <div>
              <div className="text-xs font-black uppercase tracking-[0.28em] text-cyan-300">NULLWORKS / LEGALFLOW</div>
              <h1 className="mt-2 text-3xl font-black tracking-[-0.04em] sm:text-4xl">TalkingParents Evidence Portal</h1>
              <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">
                Load the two verified exports once, search all 1,340 source pages, and jump directly to an exact screenshot-ready PDF page.
              </p>
            </div>
            <button onClick={lock} className="rounded-xl border border-white/15 px-4 py-2 text-xs font-black uppercase tracking-[0.16em] text-slate-300 hover:bg-white/5">Lock</button>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <Stat label="Message index" value={`${indexedMessagePages.toLocaleString()} / 1,241 pages`} />
            <Stat label="Calendar index" value={`${indexedCalendarPages} / 99 pages`} />
            <Stat label="Integrity check" value="SHA-256 verified before indexing" />
            <Stat label="Source handling" value="PDFs and searches stay on device" />
          </div>
        </header>

        <section className="mt-5 grid gap-5 lg:grid-cols-[340px_1fr]">
          <aside className="space-y-5">
            <div className="rounded-[26px] border border-white/10 bg-[#0d202a] p-5">
              <div className="text-xs font-black uppercase tracking-[0.22em] text-cyan-300">1. Load and index originals</div>
              <p className="mt-3 text-sm leading-6 text-slate-400">
                Select both unmodified TalkingParents PDFs. The browser verifies each SHA-256 receipt, extracts the text locally, and retains the source for exact-page rendering.
              </p>
              <label className="mt-4 block cursor-pointer rounded-2xl bg-cyan-300 px-4 py-3 text-center text-xs font-black uppercase tracking-[0.16em] text-slate-950">
                Select PDF file(s)
                <input type="file" accept="application/pdf,.pdf" multiple className="hidden" onChange={loadFiles} />
              </label>
              <div className="mt-4 space-y-2 text-xs">
                {RECORDS.map((record) => {
                  const itemProgress = progress[record.key];
                  const complete = itemProgress?.current === itemProgress?.total;
                  return (
                    <div key={record.key} className={`rounded-xl border p-3 ${loadedLabels[record.key] ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-200" : "border-white/10 bg-black/20 text-slate-500"}`}>
                      <strong>{record.key === "messages" ? "Messages" : "Calendar"}:</strong> {loadedLabels[record.key] ?? "not loaded"}
                      {itemProgress && !complete && (
                        <div className="mt-2">
                          <div className="h-2 overflow-hidden rounded-full bg-black/30"><div className="h-full bg-cyan-300" style={{ width: `${(itemProgress.current / itemProgress.total) * 100}%` }} /></div>
                          <div className="mt-1">Indexing {itemProgress.current.toLocaleString()} / {itemProgress.total.toLocaleString()} pages</div>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
              {pdfError && <div className="mt-3 rounded-xl border border-red-400/30 bg-red-950/30 p-3 text-xs leading-5 text-red-200">{pdfError}</div>}
            </div>

            <div className="rounded-[26px] border border-white/10 bg-[#0d202a] p-5">
              <div className="text-xs font-black uppercase tracking-[0.22em] text-cyan-300">Source receipts</div>
              <div className="mt-4 space-y-4">
                {RECORDS.map((record) => (
                  <div key={record.key} className="rounded-2xl border border-white/10 bg-black/20 p-4 text-xs leading-5 text-slate-400">
                    <div className="font-black text-white">{record.label}</div>
                    <div className="mt-2">Auth: <span className="font-mono text-cyan-200">{record.auth}</span></div>
                    <div>Pages: {record.pages}</div>
                    <div>Generated: {record.generated}</div>
                    <div className="mt-2 break-all font-mono text-[10px] text-slate-500">SHA-256: {record.sha256}</div>
                  </div>
                ))}
              </div>
            </div>
          </aside>

          <section>
            <div className="sticky top-3 z-10 rounded-[26px] border border-white/10 bg-[#0d202a]/95 p-4 shadow-xl shadow-black/20 backdrop-blur">
              <div className="grid gap-3 sm:grid-cols-[1fr_auto]">
                <input
                  value={query}
                  onChange={(event) => setQuery(event.target.value)}
                  placeholder='Search exact words, e.g. "financial documents" or tutoring'
                  className="min-w-0 rounded-2xl border border-white/15 bg-black/30 px-5 py-4 text-base outline-none ring-cyan-300 placeholder:text-slate-600 focus:ring-2"
                />
                <select value={recordFilter} onChange={(event) => setRecordFilter(event.target.value as "all" | RecordKey)} className="rounded-2xl border border-white/15 bg-[#102733] px-4 py-3 text-sm font-bold outline-none">
                  <option value="all">All records</option>
                  <option value="messages">Messages only</option>
                  <option value="calendar">Calendar only</option>
                </select>
              </div>
              <div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs text-slate-500">
                <span>{query.trim() ? `${results.length} ranked page matches` : pages.length ? "Showing first 50 indexed pages" : "Load a source PDF to begin"}</span>
                <span>Search is performed entirely in this browser session.</span>
              </div>
            </div>

            <div className="mt-4 space-y-3">
              {results.map((result) => {
                const recordMeta = RECORDS.find((record) => record.key === result.record);
                return (
                  <article key={result.id} className="rounded-[24px] border border-white/10 bg-[#0d202a] p-5 shadow-lg shadow-black/10">
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div className="min-w-0">
                        <div className="flex flex-wrap gap-2 text-[10px] font-black uppercase tracking-[0.16em]">
                          <span className="rounded-full bg-cyan-300/10 px-3 py-1 text-cyan-200">{result.record}</span>
                          <span className="rounded-full bg-white/5 px-3 py-1 text-slate-400">Page {result.page} of {result.totalPages}</span>
                          {result.dates.slice(0, 3).map((date) => <span key={date} className="rounded-full bg-white/5 px-3 py-1 text-slate-500">{date}</span>)}
                        </div>
                        <h2 className="mt-3 text-xl font-black tracking-[-0.02em] text-white"><Highlight text={result.title} terms={terms} /></h2>
                      </div>
                      <div className="text-right text-[10px] text-slate-600">Auth {recordMeta?.auth}</div>
                    </div>
                    <p className="mt-3 text-sm leading-7 text-slate-300"><Highlight text={result.snippet} terms={terms} /></p>
                    <div className="mt-4 flex flex-wrap gap-2">
                      <button onClick={() => void openViewer(result)} className="rounded-xl bg-cyan-300 px-4 py-2 text-xs font-black uppercase tracking-[0.12em] text-slate-950">View exact PDF page</button>
                      <button onClick={() => void copyCitation(result)} className="rounded-xl border border-white/15 px-4 py-2 text-xs font-black uppercase tracking-[0.12em] text-slate-300 hover:bg-white/5">Copy source citation</button>
                    </div>
                  </article>
                );
              })}
              {!pages.length && <div className="rounded-[24px] border border-white/10 bg-[#0d202a] p-8 text-center text-slate-400">Select the authenticated PDF exports on the left. The 99-page calendar should index quickly; the 1,241-page message record may take several minutes on a phone.</div>}
              {pages.length > 0 && !results.length && <div className="rounded-[24px] border border-white/10 bg-[#0d202a] p-8 text-center text-slate-400">No page contains every search term. Try fewer or more specific words.</div>}
            </div>
          </section>
        </section>
      </div>

      {viewer && (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-black/90 p-2 sm:p-5">
          <div className="mx-auto max-w-6xl rounded-[24px] border border-white/15 bg-[#0d202a] shadow-2xl">
            <div className="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 border-b border-white/10 bg-[#0d202a]/95 p-4 backdrop-blur">
              <div>
                <div className="text-xs font-black uppercase tracking-[0.16em] text-cyan-300">{viewer.record} · source page {viewer.page} of {viewer.totalPages}</div>
                <div className="mt-1 max-w-2xl truncate text-sm font-bold text-white">{viewer.title}</div>
              </div>
              <div className="flex flex-wrap gap-2">
                <button onClick={() => setZoom((value) => Math.max(0.65, value - 0.15))} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-black">−</button>
                <button onClick={() => setZoom(1.1)} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-black">Fit</button>
                <button onClick={() => setZoom((value) => Math.min(2.5, value + 0.15))} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-black">+</button>
                <button onClick={() => void copyCitation(viewer)} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-black">Copy citation</button>
                <button onClick={() => openNativePdf(viewer)} className="rounded-xl border border-white/15 px-3 py-2 text-xs font-black">Open PDF ↗</button>
                <button onClick={savePng} className="rounded-xl bg-cyan-300 px-3 py-2 text-xs font-black text-slate-950">Save page PNG</button>
                <button onClick={() => setViewer(null)} className="rounded-xl bg-white px-3 py-2 text-xs font-black text-slate-950">Close</button>
              </div>
            </div>
            <div ref={canvasWrapRef} className="min-h-[60vh] overflow-auto p-3 text-center sm:p-6">
              {rendering && <div className="mb-3 text-xs font-black uppercase tracking-[0.18em] text-cyan-300">Rendering original page…</div>}
              <canvas ref={canvasRef} className="mx-auto max-w-none bg-white shadow-2xl" />
            </div>
          </div>
        </div>
      )}
    </main>
  );
}
